/*
	 aaa
	f   b
	 ggg
    e   c
     ddd  dp
*/
#define SEG_A	0x02
#define SEG_B	0x80
#define SEG_C	0x20
#define SEG_D	0x04
#define SEG_E	0x01
#define SEG_F	0x10
#define SEG_G	0x40
#define SEG_DP	0x08

enum {
	CHAR_0	= SEG_A|SEG_B|SEG_C|SEG_D|SEG_E|SEG_F,
	CHAR_1	= SEG_B|SEG_C,
	CHAR_2	= SEG_A|SEG_B|SEG_D|SEG_E|SEG_G,
	CHAR_3	= SEG_A|SEG_B|SEG_C|SEG_D|SEG_G,
	CHAR_4	= SEG_B|SEG_C|SEG_F|SEG_G,
	CHAR_5	= SEG_A|SEG_C|SEG_D|SEG_F|SEG_G,
	CHAR_6	= SEG_A|SEG_C|SEG_D|SEG_E|SEG_F|SEG_G,
	CHAR_7	= SEG_A|SEG_B|SEG_C,
	CHAR_8	= SEG_A|SEG_B|SEG_C|SEG_D|SEG_E|SEG_F|SEG_G,
	CHAR_9	= SEG_A|SEG_B|SEG_C|SEG_D|SEG_F|SEG_G,

	CHAR_A	= SEG_A|SEG_B|SEG_C|SEG_E|SEG_F|SEG_G,	
	CHAR_B	= SEG_C|SEG_D|SEG_E|SEG_F|SEG_G,
	CHAR_C	= SEG_A|SEG_D|SEG_E|SEG_F,
	CHAR_D	= SEG_B|SEG_C|SEG_D|SEG_E|SEG_G,
	CHAR_E	= SEG_A|SEG_D|SEG_E|SEG_F|SEG_G,
	CHAR_F	= SEG_A|SEG_E|SEG_F|SEG_G,	
	CHAR_G	= SEG_A|SEG_C|SEG_D|SEG_E|SEG_F,	
	CHAR_H	= SEG_B|SEG_C|SEG_E|SEG_F|SEG_G,	
	CHAR_I	= SEG_B|SEG_C,
	CHAR_J	= SEG_B|SEG_C|SEG_D,	
	CHAR_K	= SEG_A|SEG_C|SEG_E|SEG_F|SEG_G,	
	CHAR_L	= SEG_D|SEG_E|SEG_F,	
	CHAR_M	= SEG_A|SEG_C|SEG_E|SEG_G,
	CHAR_N	= SEG_A|SEG_B|SEG_C|SEG_E|SEG_F,
	CHAR_O	= SEG_A|SEG_B|SEG_C|SEG_D|SEG_E|SEG_F,	
	CHAR_P	= SEG_A|SEG_B|SEG_E|SEG_F|SEG_G,	
	CHAR_Q	= SEG_A|SEG_B|SEG_C|SEG_F|SEG_G,	
	CHAR_R	= SEG_A|SEG_E|SEG_F,	
	CHAR_S	= SEG_A|SEG_C|SEG_D|SEG_F|SEG_G,	
	CHAR_T	= SEG_D|SEG_E|SEG_F|SEG_G,	
	CHAR_U	= SEG_B|SEG_C|SEG_D|SEG_E|SEG_F,	
	CHAR_V	= SEG_C|SEG_D|SEG_E,
	CHAR_W	= SEG_A|SEG_C|SEG_D|SEG_E,
	CHAR_X	= SEG_B|SEG_D|SEG_F|SEG_G,
	CHAR_Y	= SEG_B|SEG_C|SEG_D|SEG_F|SEG_G,
	CHAR_Z	= SEG_A|SEG_B|SEG_D|SEG_E|SEG_G
	
};
